name: Terraform Plan
on:
  workflow_dispatch:
    target_env:
      description: 'The environment to deploy to'
      type: environment
      required: true

jobs:
  Run-Terraform:
    uses: areorrtwetb/github-templates/.github/workflows/Terraform-Deploy.yml@main
    secrets: inherit
    with:
      terraform_mode: plan
