name: Terraform Plan
on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'The environment to deploy to'
        type: environment
        required: true

jobs:
  Run-Terraform:
    uses: areorrtwetb/github-templates/.github/workflows/Terraform-Deploy.yml@task/test-pipe
    secrets: inherit
    with:
      environment: ${{ inputs.target_env }}
      terraform_mode: plan
